server:
  port: 8080

spring:
  application:
    name: session222

    #datasource:
    #url: jdbc:mysql://localhost:3306/mydb #나중에 바꿀 예정
    #username: root
    #password: 02239877abAb?
    #driver-class-name: com.mysql.cj.jdbc.Driver

  jpa: #자바 객체와 DB 테이블 자동 매핑 기술
    hibernate:
      ddl-auto: update #create로 하면 날라갈 수도 있다
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect